<?php

require_once (dirname(dirname(__FILE__)) . '\..\functions\dbFunctions.php');

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-11-21 at 17:00:06.
 */
class connectionTest extends PHPUnit_Framework_TestCase {
    /**
     * @backupGlobals disabled
     * @backupStaticAttributes disabled
     */

    /**
     * @var connection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new connection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert getConnection() != null.
     *
     * @covers connection::getConnection
     */
    public function testGetConnection() {
        $this->assertNotEquals(
                null
                , $this->object->conn
        );
    }

    /**
     * @covers connection::getRow
     * @depends testGetConnection
     */
    public function testGetRow() {
        $sql = 'SELECT * FROM books';
        $rows = $this->object->getRow($sql);

        while ($row = $rows->fetch()) {
            $this->assertObjectHasAttribute(
                    'name'
                    , $row
            );
        }
    }

}
